### ISSUE TITLE
Cointhing will occasionally freeze and need a restart

### ISSUE THREAD

**Issue by stavrjim** [barn53/CoinThing#11]
Hello, I have a problem with the cointhing that appeared again after I thought it was resolved when I had one replaced earlier in the year. Basically, it will power up, connect and fetch the current price. The heartbeat will pulse for about a minute. After that the heartbeat stops, the updates stop and the internal URL becomes unreachable until I power it off and on again. It is running version 1.2 of the cointhing software, so not sure if updating the software will solve it. I have tried powering it up using PC USB, different PC USB (3.1), wall chargers, the problem remains. I tried setting port forwarding for SSL and HTTP, problem remains, tried creating a DMZ and putting it on it, problem remains. For a while it worked just fine, now the same problem I had with the original cointhing has resurfaced. Any help or pointers would be appreciated.

**Comment by barn53** [comment]
Hello,

that sounds very strange to me.
I have quite a lot of devices out and not one similar problem – and you
have it twice...
You have made many attempts to solve the problem.
The only other thing I can think of that you should try is to update the
firmware to the latest version.

You can find the files and instructions here:
https://barn53.github.io/CoinThing/#available-versions-to-download

Download the files:
- spiffs_v1.4.0.bin
- cointhing_v1.4.4.bin

You should update the firmware via the python script and erase the whole
memory before updating:

python -m esptool erase_flash

python -m esptool --before default_reset --after hard_reset --chip esp8266
--baud 460800 write_flash 0x0 <path_to_download>/cointhing_v1.4.4.bin
0x200000 <path_to_download>/spiffs_v1.4.0.bin

I hope, this helps.
Regards,
Gerd
