### ISSUE TITLE
Newbie problems !  :)

### ISSUE THREAD

**Issue by alpozdemir** [barn53/CoinThing#13]
Hi there,

I want to do a CoinThing too..

I have a lot of questions... :)

Which specific revision/model of 8266 do you use?(there are so many)
Which development environment or IDE should I use?  Arduino Defaul IDE is enough?

**Comment by barn53** [comment]
Hi,
you can use any of the ESP8266 modules out there, as long as there are all needed GPIO pins broken out.
You can start e.g. with a NodeMCU Dev Board like this: http://www.ai-thinker.com/pro_view-67.html

The project itself uses a custom made PCB. Here is the schematics:
![image](https://user-images.githubusercontent.com/6941379/145626207-f3c9a1a4-2411-409e-904d-5116916e594f.png)

As development environment I would not recommend Arduino IDE.
The best choice in my opinion is Visual Studio Code with the PlatformIO extension.
There is already a setting for this IDE here in the repository: platformio.ini

**Comment by barn53** [comment]
Sorry, wrong schematics... here comes the correct one:
![image](https://user-images.githubusercontent.com/6941379/145626744-0ef079b2-fc3c-467d-b49a-2edfb34d2e3a.png)
