### ISSUE TITLE
Can't connect via esptool

### ISSUE THREAD

**Issue by Nadineli** [barn53/CoinThing#14]
Hello,

i am trying to update to the latest firmware but am facing issues connecting to the device via esptool.

After i manually installed the windows drivers as mentioned in the documentation, the CoinThing is showing as connected in device manager as "Silicon Labs CP210x USB to UART Bridge (COM4)" . 
However, when i run the command _python -m esptool --no-stub chip_id_, i always get the following response (no matter which usb cable or port i try): 

> esptool.py v3.2
> Found 4 serial ports
> Serial port COM4
> COM4 failed to connect: could not open port 'COM4': OSError(22, 'Ein nicht vorhandenes Gerät wurde angegeben.', None, 433)
> Serial port COM4
> COM4 failed to connect: could not open port 'COM4': OSError(22, 'Ein nicht vorhandenes Gerät wurde angegeben.', None, 433)
> Serial port COM3
> COM3 failed to connect: could not open port 'COM3': OSError(22, 'Ein nicht vorhandenes Gerät wurde angegeben.', None, 433)
> Serial port COM1
> Connecting......................................
> COM1 failed to connect: Failed to connect to Espressif device: No serial data received.
> For troubleshooting steps visit: https://github.com/espressif/esptool#troubleshooting
> 
> A fatal error occurred: Could not connect to an Espressif device on any of the 4 available serial ports.

The actual error message translates to something like " A non existing device was specified". I've checked online but haven't been able to find a solution. 

BTW Really nice piece of work! The only reason why i wanted to update is that i wanted to see if the "24h" symbol is only in the left corner in the latest version and not in front of the current bit of the chart (it switches from left to right in 1.44). The right side wouldn't be so bad if the charts always went up :P 

Cheers and keep up the great work!

**Comment by barn53** [comment]
Hi, this seems very odd to me.
I never encountered a problem like this with the ESP.
What platform do you use, windows, I think?
I wonder if it's correct that you have 4 serial ports available (COM4, COM4, COM3, COM1)?
What version do your CoinThing have?
I cannot remember to have changed the logic where to place the chart period.
It just looks in which half the chart minimum is and puts the period into the other half.
Regards.

**Comment by Nadineli** [comment]
Hi,

thanks for the reply. Yeah i'm on Windows 10 and the CoinThig is on 1.4.4.

The COM ports match the ones showing in device manager (one of my bluetooth devices also gets assigned to COM4 just as the CoinThing). However, even when i disconnect everything else and there's only COM1 and COM4 left, i still get the same error message for the CoinThing on COM4:

> Found 2 serial ports
> Serial port COM4
> COM4 failed to connect: could not open port 'COM4': OSError(22, 'Ein nicht vorhandenes Gerät wurde angegeben.', None, 433)
> Serial port COM1
> Connecting......................................
> COM1 failed to connect: Failed to connect to Espressif device: No serial data received.
> For troubleshooting steps visit: https://github.com/espressif/esptool#troubleshooting
> 
> A fatal error occurred: Could not connect to an Espressif device on any of the 2 available serial ports.

Over the next weeks, i'll have access to some laptops where i'll try to run it from. However they are on older windows versions so hopefully there won't be any other issues with python etc :p

Also thanks for the explanation about the chart period. That makes sense

Cheers

**Comment by barn53** [comment]
Hi, by the way, I did not ship a CoinThing with version 1.4.4.
So an update on your side must have been already successful..?

**Comment by Nadineli** [comment]
Oh you just made me realize that i probably bought it off someone else other than you then because it deffo came with 1.4.4.

I was searching for a coin tracker on ebay and bought the nicest one i could find without doing any further research. Sorry for that. Next purchase will be via tindie.
