### ISSUE TITLE
Alert coingecko

### ISSUE THREAD

**Issue by mikper29** [barn53/CoinThing#17]
Hello,
Would it be possible to associate the alerts of are portfoliot coingecko with cointhing in the future.
With a headband and buzzer.

I noticed that the cointhing crashed or lost these identifiers when opening the Ultimaker Cura software.

**Comment by barn53** [comment]
I don't plan to implement this.
I don't understand your last sentence ... cura is a slicer? cointhing crashed? identifiers?
