### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by holyape** [barn53/CoinThing#19]
Hi! Unfortunately, when trying to build the project in PlatformIO, it fails with the same response:

`FileNotFoundError: [Errno 2] No such file or directory: 'secrets/secrets.json'`

It seems like the file is really missing - how can I get or generate one by myself?

**Comment by barn53** [comment]
Hi, you are right. This file is missing, since it holds the wifi credentials.
I added a file secrets/rename_to_secrets.json. You can rename it and provide your credentials.
Or leave them out. These are optional.
