### ISSUE TITLE
Improvements/Issue

### ISSUE THREAD

**Issue by RodAus** [barn53/CoinThing#21]
- On the graphic line. Pixels that go up in green, change to red when going down. (only the period, not all line). Make it easy to see from far how many times went up and down for how long. Like on tradingview com
- For example, at me moment the BTC 30d period fluctuation is +16.65% is the same as 48h. Wasn't changing when the display changed to 48h period fluctuation.
Thanks, great project!

**Comment by barn53** [comment]
Nice Idea, but I won't implement it.
You can :-)
