### ISSUE TITLE
Chart Period fix

### ISSUE THREAD

**Issue by danielkubat** [barn53/CoinThing#4]
firmware: `v1.4.2`

I believe, that values in _Chart Period_ should be mutually exclusive because only one graph can be shown in one moment. So very same approach as for _Chart Swap Interval_ section:

![chart_period](https://user-images.githubusercontent.com/42444343/128005697-543164d7-7f3d-4eb0-bfe0-7cc10719e0b5.png)

**Comment by barn53** [comment]
Chart period for "One Coin" display is not mutually exclusive, as in this mode the selected charts are cycled though.

**Comment by barn53** [comment]
Chart period for "Multiple Coins" display is mutually exclusive, as only one chart type is displayed.
