### ISSUE TITLE
Number Format fix for One Coin tab

### ISSUE THREAD

**Issue by danielkubat** [barn53/CoinThing#5]
firmware: `v1.4.2`

I believe that _Number Format_ section in _One Coin_ tab should only display one configuration row, because only one number (price) can be shown in one moment.

![format_number](https://user-images.githubusercontent.com/42444343/128006261-9fea005d-1247-4e2c-af10-71a5eb700b04.png)

**Comment by barn53** [comment]
If you look closely, you see these are six different number formats. The selected format defines the format for all displayed numbers.

**Comment by danielkubat** [comment]
sorry, I overlooked this, you are right.
