### ISSUE TITLE
Admin section isn't documented

### ISSUE THREAD

**Issue by danielkubat** [barn53/CoinThing#6]
I'm not sure whether this is intentionally or not, but `http://<ip>/admin.html` is undocumented.

Considering extended functionalities such as _Self Test_ or various _Reset_ options, I believe that such page should be part of documentation and/or link should be part of `http://<ip>/settings.html`.

**Comment by barn53** [comment]
This is intentionally not documented, as the average user does not take any advantage of this page. It would only cause questions. I use this page (or API) internally for testing and preparing delivery.
