### ISSUE TITLE
RUNE (THORChain) showing the wrong price

### ISSUE THREAD

**Issue by mariodigital** [barn53/CoinThing#7]
Currently my Cointhing shows me RUNE with a price of around $429.58, its actual price of this moment is $11,09. I tried changing the number format, but it doesn't help.

**Comment by barn53** [comment]
Hello,
the thing here is that "rune" is abiguous on coin gecko.
CoinThing allows symol names and coin gecko ids as input.
In this case it takes the not intended asset.
So you should input the coin gecko id "THORChain" into the settings to get
what you want.
Hope that helps.
Regards.



Am Mo., 6. Sept. 2021 um 10:16 Uhr schrieb Mario Digital <
***@***.***>:
